name: First Actions
on: push

jobs:
    first-workflow-under-workflow:
        name: first-workflow-job
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code repository
              uses: actions/checkout@v4
            
            - name: LIST and READ FILES using multi line commands
              run: |
                   echo "Hello reader"
                   ls -ltra
                   cat README.md
            
            # - name: list files
            #   run: ls

            # - name: READ readme.md
            #   run: cat README.md